CREATE DATABASE awd_projekt;
USE awd_projekt;

CREATE TABLE `awd_projekt`.`user` ( `ID` INT NOT NULL AUTO_INCREMENT , `USERNAME` VARCHAR(42) NOT NULL , `EMAIL` VARCHAR(255) NOT NULL , `PASSWORD` VARCHAR(255) NOT NULL , `SALT` VARCHAR(255) NOT NULL , `REGISTERED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`ID`), UNIQUE (`USERNAME`), UNIQUE (`EMAIL`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

CREATE TABLE `awd_projekt`.`tag` ( `ID` INT NOT NULL AUTO_INCREMENT , `NAME` VARCHAR(255) NOT NULL , `CREATED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`ID`), UNIQUE (`NAME`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

CREATE TABLE `awd_projekt`.`image` ( `ID` INT NOT NULL AUTO_INCREMENT , `NAME` VARCHAR(255) NOT NULL , `DESCRIPTION` TEXT NULL , `PATH` VARCHAR(255) NOT NULL , `IMG_USER_ID` INT NOT NULL , `PRIVATE` TINYINT(1) NOT NULL , UNIQUE (`PATH`), `UPLOADED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`ID`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

CREATE TABLE `awd_projekt`.`comment` ( `ID` INT NOT NULL AUTO_INCREMENT , `CONTENT` TEXT NOT NULL, `CMT_USER_ID` INT NOT NULL , `CMT_IMAGE_ID` INT NOT NULL , `CMT_PARENT_ID` INT NULL , `POSTED_ON` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`ID`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

CREATE TABLE `awd_projekt`.`image_tag` ( `ID` INT NOT NULL AUTO_INCREMENT , `IMAGE_ID` INT NOT NULL , `TAG_ID` INT NOT NULL , PRIMARY KEY (`ID`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_general_ci;

CREATE USER 'php_projekt'@'localhost' IDENTIFIED BY 'php_projekt';GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'php_projekt'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;